metrics_port: 8080
disable_golang_metrics: false
db_path: asn.csv
log_file: /tmp/tracer.log
db_update_interval: 24h
db_update_source: updated_asn.csv
# db_update_source: https://example.com/asn.csv
targets:
  - host: 1.1.1.1  # Cloudflare DNS
    schedule: "@every 300s"
  - host: 8.8.8.8  # Google DNS
    schedule: "@every 300s"
  - host: google.com
    schedule: "@every 300s"
  - host: www.akamai.com  # Akamai CDN
    schedule: "@every 300s"