# Main configuration settings
metrics_port: 8080  # Prometheus metrics port
db_path: GeoLite2-ASN.mmdb
# log_file: tracer.log  # Log file location
targets:
  - host: 1.1.1.1  # Cloudflare DNS
    schedule: "@every 300s"
  - host: api.sandbox.push.apple.com # Apple APN
    schedule: "@every 300s"
  - host: 8.8.8.8  # Google DNS
    schedule: "@every 300s"
