# Configuration for tracer
metrics_port: 8080  # Prometheus metrics port
db_path: GeoLite2-ASN.mmdb  # Path to MaxMind GeoLite2-ASN database
log_file: tracer.log  # Log output file
db_update_interval: 24h  # Check for updates every 24 hours
db_update_source: https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-ASN&license_key=YOUR_KEY&suffix=tar.gz  # MaxMind API URL
maxmind_license_key: YOUR_KEY  # MaxMind license key for API downloads
targets:
  - host: 1.1.1.1  # Cloudflare DNS
    schedule: "@every 300s"
  - host: 8.8.8.8  # Google DNS
    schedule: "@every 300s"
  - host: google.com
    schedule: "@every 300s"
  - host: www.akamai.com  # Akamai CDN
    schedule: "@every 300s"